# Generated by Django 5.0.3 on 2024-04-03 20:11

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_category_sight_delete_marker_delete_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=' name of the Location', max_length=225, verbose_name='location name')),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('image', models.ImageField(blank=True, null=True, upload_to='location_images/')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.category')),
            ],
            options={
                'verbose_name_plural': 'Areas',
            },
        ),
    ]
