# Generated by Django 5.0.3 on 2024-08-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Woodland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[(' Insects', ' Insects '), ('Plants', 'Plants'), ('Birds', 'Birds'), ('Animal', 'Animals')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Woodlands',
            },
        ),
    ]
