# Generated by Django 5.0.3 on 2024-08-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodland', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woodland',
            name='category',
            field=models.CharField(choices=[('Insects', 'Insects'), ('Plants', 'Plants'), ('Birds', 'Birds'), ('Animal', 'Animals')], max_length=20),
        ),
    ]
