# Generated by Django 5.0.3 on 2024-07-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default_profile_image.png', null=True, upload_to='images/'),
        ),
    ]
